### ISSUE TITLE
Change Text in CompSoc page under SIGs

### ISSUE THREAD

**Issue by kaushiksk** [IEEE-NITK/ieee-nitk.github.io#131]
Firstly `COMPSOC` should be changed to `CompSoc`. And the description should reflect the reorganization into Research Groups. Also the text might look better if it is center aligned than the left align that is currently used.

In https://ieeenitk.org/compsoc.html,

We need to add the details of the core members and the research groups as well.

**Comment by salman-bhai** [comment]
@kaushiksk could you suggest a general layout for the page. Essentially I'd like to model it as the follows:
1. IEEE CompSoc - Description
2. Details about Research Groups
3. Members in each Research Group and activities of the Research Group

**Comment by kaushiksk** [comment]
I think we can add a general description of Compsoc and mention the three research groups. Then a "Read More" button that links to a detailed page.

**Comment by salman-bhai** [comment]
@pvgupta24 let the design remain the same. Content for now, the one that you have put is fine. Further changes will be suggested by @kaushiksk 
Including last year's projects is definitely a must and that looks good!
Old Project info preferably replaced as of now!
