### ISSUE TITLE
Add Information about Women's Hackathon on WiE Page

### ISSUE THREAD

**Issue by salman-bhai** [IEEE-NITK/ieee-nitk.github.io#180]
- [x] Add Poster for the Hackathon
- [x] Small Description about the event
- [x] Images related to the event from the Google Photos Link

**Comment by anumehaagrawal** [comment]
@SaurabhAgarwala  Whats the status on this ?

**Comment by SaurabhAgarwala** [comment]
Really sorry. It completely slipped out of my mind. Will do it now.

**Comment by SaurabhAgarwala** [comment]
Please share with me the links to the images related to the event, I couldn't find it in Google Photos.

**Comment by salman-bhai** [comment]
https://photos.app.goo.gl/Q732uVM8fvaSeyS38

@SaurabhAgarwala kindly find the photos attached in this link. Cheers!

**Comment by SaurabhAgarwala** [comment]
Sure, will update it after the endsems.

**Comment by nimbus98** [comment]
@SaurabhAgarwala  Updates on this?

**Comment by SaurabhAgarwala** [comment]
Oops! Will do it by tomorrow.
