### ISSUE TITLE
Events Section Update Needed

### ISSUE THREAD

**Issue by SamarthBonthala** [IEEE-NITK/ieee-nitk.github.io#185]
Please take a look at the picture below and try to correct the same.
![image](https://user-images.githubusercontent.com/20479421/50077873-976e6100-020b-11e9-90c7-46302b80a00f.png)
Content on left side going out of limit 
![image](https://user-images.githubusercontent.com/20479421/50077907-a48b5000-020b-11e9-9d0a-33c5e2ed03f1.png)

**Comment by nimbus98** [comment]
I'll fix it
