### ISSUE TITLE
Changes in Events section of website

### ISSUE THREAD

**Issue by SamarthBonthala** [IEEE-NITK/ieee-nitk.github.io#198]
Please make changes to the event names and ensure they fit in the space allotted on left side of the webpage and add the new events we conducted this year - WiTS, Embedathon in this section

![image](https://user-images.githubusercontent.com/20479421/51621434-86c3b000-1f5a-11e9-9531-ce3d196c9d37.png)

WiTS link can be removed from first page of the website

**Comment by nimbus98** [comment]
The issue is fixed.
