### ISSUE TITLE
Fix header

### ISSUE THREAD

**Issue by anumehaagrawal** [IEEE-NITK/ieee-nitk.github.io#217]
The logo should be inside the header and not midway
![Screenshot from 2019-04-21 12-57-51](https://user-images.githubusercontent.com/25412153/56466867-1e8b4a00-6435-11e9-8691-49160ae73c0a.png)

**Comment by anumehaagrawal** [comment]
@nimbus98  Any updates on this ?

**Comment by nimbus98** [comment]
Will be updated along with home page and team section after the latest blogs are merged, possibly this weekend.

**Comment by nimbus98** [comment]
Its been fixed
