### ISSUE TITLE
CI/CD for blog

### ISSUE THREAD

**Issue by pvgupta24** [IEEE-NITK/ieee-nitk.github.io#270]
- Setup CI/CD for building the blog and deploying to a different branch (that will be used to host gh-pages)
- This will keep the dev branch clean and it won't need the compiled files which is very messy to work with right now and leads to lot of merge conflicts

**Comment by salman-bhai** [comment]
So we do currently have a Travis pipeline which runs which checks if the code has compiled and is built successfully or not. You can check if we need to do any modifications there.

**Comment by pvgupta24** [comment]
Plan is to separate out the blog to a new repo with called `blog`.
Master branch can contain just the articles markdown files, without the compiled files. Commits will trigger a build and update another gh-pages branch (which shouldn't be tampered manually).

This will reduce merge conflicts when adding new blog articles and won't clutter website repo.

@nimbus98 @salman-bhai
