### ISSUE TITLE
Current members in Alumni List

### ISSUE THREAD

**Issue by nishant-nayak** [IEEE-NITK/ieee-nitk.github.io#392]
Some current members of the club (Sunaina, Shannon, Madhav, Anirudh Prabhakaran, etc.) are present in the alumni list. Go through the list of alumni and ensure that the entire passed out batch and **only** the passed out batch is added in as alumni.

**Comment by Vignaraj-pai** [comment]
Oh shoot. Will fix that

**Comment by nishant-nayak** [comment]
Most names were removed in #394, but some names are still yet to be removed:
- Spandan Patkar
- Shivani Chanda
- Amruth Raj P
- Madhav Kumar

Remove these names from the alumni section too.
