### ISSUE TITLE
Unable to run on local system

### ISSUE THREAD

**Issue by salman-bhai** [IEEE-NITK/ieee-nitk.github.io#47]
I've been getting the following error log on my local system. Any recent major changes that were made to the blog. Also when I run `bundle exec jekyll serve` it gives me an error for `Could not locate Gemfile or .bundle/ directory` as the error. 

Here is the Error Log
```
/var/lib/gems/2.3.0/gems/jekyll-3.5.2/lib/jekyll/drops/document_drop.rb:8: warning: already initialized constant Jekyll::Drops::DocumentDrop::NESTED_OBJECT_FIELD_BLACKLIST
/usr/lib/ruby/vendor_ruby/jekyll/drops/document_drop.rb:8: warning: previous definition of NESTED_OBJECT_FIELD_BLACKLIST was here
/var/lib/gems/2.3.0/gems/jekyll-3.5.2/lib/jekyll/drops/drop.rb:8: warning: already initialized constant Jekyll::Drops::Drop::NON_CONTENT_METHODS
/usr/lib/ruby/vendor_ruby/jekyll/drops/drop.rb:8: warning: previous definition of NON_CONTENT_METHODS was here

Source: /home/salman/All-Projects/Personal-Project/ieee-nitk.github.io
Destination: /home/salman/All-Projects/Personal-Project/ieee-nitk.github.io/_site
Incremental build: enabled
Generating... 
    done in 0.159 seconds.
jekyll 3.1.6 | Error:  undefined method `bash_on_windows?' for Jekyll::Utils::Platforms:Module
```

Let me know if there is any dependency unresolved!

**Comment by adithyabhatkajake** [comment]
Did you try a git pull before running the build? When was the last pull you made?

**Comment by viggi-v** [comment]
wasn't the pagination issue solved? else try `gem install jekyll-paginate`

**Comment by salman-bhai** [comment]
@adithyabhatkajake I did try that! Unfortunately no that didn't solve the Issue!
@viggi-v the pagination isn't an Issue

**Comment by adithyabhatkajake** [comment]
Why do you run `bundle exec jekyll serve`? Just `jekyll serve` should work. Can you also post the exact commands you run, the version of jekyll, gem and bundler and their verbose outputs when you run them?

**Comment by adithyabhatkajake** [comment]
Use `git log --oneline` to view the list of commits. Run `git checkout <Commit hash>` to see which commit onwards you cannot run `jekyll serve`. Don't forget to `git checkout master` before doing any changes.

**Comment by salman-bhai** [comment]
@adithyabhatkajake if I run `jekyll serve` I get this verbose! 
jekyll version is 3.1.6
Bundler version 1.15.4

Which gem version do you want?

**Comment by adithyabhatkajake** [comment]
I am using jekyll v3.5.1 and bundler v1.15.3. Seems like this issue is local to you. @viggi-v Are you on ubuntu too and facing similar issues?

**Comment by salman-bhai** [comment]
Error resolved!

It seems I had two versions of Jekyll on my system!
1. Jekyll installed by `bundler`
2. Jekyll installed by `apt`

Did this to resolve it:
```
sudo apt-get remove jekyll
sudo gem uninstall jekyll
sudo gem install jekyll-seo-tag
```

Thanks for spending time on this though!
