### ISSUE TITLE
Direct people to the blog from the home page

### ISSUE THREAD

**Issue by adithyabhatkajake** [IEEE-NITK/ieee-nitk.github.io#62]
Need a jumbo Tron or hero class to direct people to the blog/Gyan from the home page. Also put featured contents and upcoming events in the carousel.

**Comment by salman-bhai** [comment]
@viggi-v Any progress or do you want a junior to work on this?

**Comment by salman-bhai** [comment]
@viggi-v ?

**Comment by salman-bhai** [comment]
@viggi-v ?

**Comment by salman-bhai** [comment]
@adithyabhatkajake could you give a rough sketch of what exactly you'd like here!

**Comment by salman-bhai** [comment]
Also why is this needed again?

**Comment by anumehaagrawal** [comment]
@salman-bhai What exactly am i supposed to do in this ?
