### ISSUE TITLE
Issues to be fixed to take part in IEEE Website Competition

### ISSUE THREAD

**Issue by adithyabhatkajake** [IEEE-NITK/ieee-nitk.github.io#76]
- [x] All websites must use WordPress themes that are checked in advance of submission and score at least a 70% or higher on themecheck.org.
- [x] All plugins must explicitly state compatibility with WordPress 4.7.5.
Note: 
The following WordPress plugins are [not allowed for use by IEEE:](http://wpengine.com/support/disallowed-plugins/). **We have a repository of photos that you may use in your design.** To access them, please visit the tab labeled Photos. You may not use either approved photographs or images that you do not own or have a valid license for.
- [x] [Digital Style Guide:](http://ieee.org/about/webteam/styleguide/index.html) – This section contains an overview of web-related requirements, best practices, and style guidelines for IEEE employees, volunteers, and partners (vendors, consultants, or contract workers) involved in the development or enhancement of IEEE websites.
    - [x]  Fonts changed according to guidelines
    - [x]   Nav Bar changed - Logo should be to the right with padding on top and bottom with a clear background . The nav bar contents should be shifted to the left
    - [x]  Footer needs to be modified according to the guidelines

- [x] [Global Page Element and Branding Requirements:](http://ieee.org/about/webteam/styleguide/page_elements_and_branding.html) – IEEE digital publishers are asked to include IEEE-wide styles when structuring websites in order to create alignment, provide orientation, leverage the IEEE brand, and prevent users from having to learn each website. IEEE styles are detailed here for use of the IEEE enterprise-wide meta-navigation, IEEE Master Brand, site identifier, IEEE favicon, and website headers and footers.
- [x] All student members’ names and IEEE member numbers
- [x] An outline of goals and objectives of the project
- [x] Original photos and/or videos

**Comment by salman-bhai** [comment]
Wordpress themes? We don't fall into that category na?

**Comment by adithyabhatkajake** [comment]
But we still have to get 70% or higher in http://themecheck.org

**Comment by salman-bhai** [comment]
Alright! No Issues there then!

**Comment by salman-bhai** [comment]
@adithyabhatkajake  last three points, how much of it do we satisfy?

**Comment by salman-bhai** [comment]
Nav Bar and Footer will be done by @mahim23

**Comment by salman-bhai** [comment]
@anumeha Add navbar and site identifier!
